import { Search, GitBranch, Code2, CheckCircle2, Rocket } from "lucide-react";
import type { Phase } from "@/types";

export const PHASES: Phase[] = [
  {
    label: "01  Product Discovery",
    short: "Discovery",
    eyebrow: "step 1",
    icon: Search,
    title: "Understand the product vision, users, workflows, and technical requirements.",
    deliverables: [
      "Product goals and users",
      "Workflow mapping",
      "Technical requirements",
    ],
    traditional: "2–3 weeks",
    tBar: 90,
    withAccelprod: "1 week",
    lBar: 28,
  },
  {
    label: "02  Architecture & Planning",
    short: "Architecture",
    eyebrow: "step 2",
    icon: GitBranch,
    title: "Define scalable system architecture, AI workflows, integrations, and delivery roadmap.",
    deliverables: [
      "System architecture",
      "AI workflow design",
      "Delivery roadmap",
    ],
    traditional: "3–5 weeks",
    tBar: 72,
    withAccelprod: "1-2 weeks",
    lBar: 34,
  },
  {
    label: "03  Rapid Engineering",
    short: "Development",
    eyebrow: "step 3",
    icon: Code2,
    title: "Build production-ready systems using AI-accelerated engineering workflows.",
    deliverables: [
      "Working product increments",
      "Backend and frontend systems",
      "Staging environments",
    ],
    traditional: "Standard pace",
    tBar: 100,
    withAccelprod: "30-50% faster",
    lBar: 58,
  },
  {
    label: "04  Iteration & Testing",
    short: "Testing",
    eyebrow: "step 4",
    icon: CheckCircle2,
    title: "Refine product experience, QA systems, performance, and reliability.",
    deliverables: [
      "QA and test coverage",
      "Performance fixes",
      "UX refinements",
    ],
    traditional: "Reactive QA",
    tBar: 76,
    withAccelprod: "Built in",
    lBar: 32,
  },
  {
    label: "05  Launch & Scale",
    short: "Launch",
    eyebrow: "step 5",
    icon: Rocket,
    title: "Deploy, monitor, optimize, and continuously improve the product.",
    deliverables: [
      "Production deployment",
      "Monitoring and analytics",
      "Post-launch iteration plan",
    ],
    traditional: "Manual handoff",
    tBar: 82,
    withAccelprod: "Launch-ready",
    lBar: 24,
  },
];
